apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::068588674253:role/eksctl-eksctl-demo-nodegroup-ng-6-NodeInstanceRole-1IL4ZG8LGHFYF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::068588674253:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-09-10T19:41:11Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "31096"
  uid: 56ec0e22-fa31-4afb-8e4d-309316fd59de
